### ISSUE TITLE
API /upload/metadata/  error on parsivel metada submission

### ISSUE THREAD

**Issue by andrecastro0o** [actris-cloudnet/dataportal#212]
I am having issues with uploading metadata  on parsivel disdrometer NetCDF files to cloudnet API

The following POST request, returns a Error 400  `'type': 'entity.parse.failed'`.

Anyone is aware of where the issue might reside? Is it because it is a parsivel NetCDF submission? 

I was able to do 2 successful uploads of parsivel metadata and file to cloudnet: https://cloudnet.fmi.fi/search/data?site=lutjewad&dateFrom=2023-11-26&dateTo=2023-11-28&product=disdrometer

@siiptuo maybe you can look at your logs and see what is failing with this request? 

```python
import requests
import json
from requests.auth import HTTPBasicAuth
from pprint import pprint

user = 'cabauw'
pwd = '???'
data = {
    # PAR002 Cabauw
    "filename": "20231125_KNMI_Cabauw-CABAUW_PAR002.nc",
    "checksum": "5add012264b6ba69862d1061901494de",
    "measurementDate": "2023-11-25",
    "instrument": "parsivel",
    "instrumentPid": "https://hdl.handle.net/21.12132/3.65ecf80219d14d1b"
}

r = requests.post('https://cloudnet.fmi.fi/upload/metadata/',
                  auth=HTTPBasicAuth(user, pwd),
                  json=json.dumps(data),
                  headers={"Content-Type": "application/json"}
)
print(r.url)
print(r.headers)
print(r.status_code)
pprint(r.json())
```
Response: 400: entity.parse.failed
```
{'server': 'nginx/1.25.3', 'date': 'Tue, 28 Nov 2023 16:02:42 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '379', 'x-powered-by': 'Express', 'etag': 'W/"17b-pmZxrwQu0fJfaJCOI30ssMPospQ"', 'set-cookie': '3866fdcd36aeaae468ebac902177effe=87502696078bf03ac4348795f82d9cc9; path=/; HttpOnly; Secure; SameSite=None'}

400

{'body': '"{\\"filename\\": \\"20231125_KNMI_Cabauw-CABAUW_PAR002.nc\\", '
         '\\"checksum\\": \\"5add012264b6ba69862d1061901494de\\", '
         '\\"measurementDate\\": \\"2023-11-25\\", \\"instrument\\": '
         '\\"parsivel\\", \\"instrumentPid\\": '
         '\\"https://hdl.handle.net/21.12132/3.65ecf80219d14d1b\\"}"',
 'expose': True,
 'status': 400,
 'statusCode': 400,
 'type': 'entity.parse.failed'}
```

thanks

**Comment by siiptuo** [comment]
It seems that you're sending the JSON as string instead of object. This can be fixed by removing the `json.dumps` call:

```python
r = requests.post('https://cloudnet.fmi.fi/upload/metadata/',
                  auth=HTTPBasicAuth(user, pwd),
                  json=data)
```

Using `json` argument should also set the `Content-Type` header automatically.

**Comment by andrecastro0o** [comment]
Yes, that's correct @siiptuo , thank you! With that correction when I make the same request I get a `409
File already uploaded` which is expected if the files is there.


Now, if I want to confirm that response and look for that file, how to do it? when:
* data portal :  does not the show file "where" it should have landed: https://cloudnet.fmi.fi/search/data?site=cabauw&dateFrom=2023-11-24&dateTo=2023-11-26&product=disdrometer
* API:  [cloudnet.fmi.fi  /api/files/ GET method](https://docs.cloudnet.fmi.fi/api/data-portal.html#get-apifilesuuid--file) only uses UUID, and not the checksum

**Comment by siiptuo** [comment]
We separate *files* and *raw files*. *Raw files* are uploaded by sites and *files* are processed products visible in the data portal. Raw files can be queried with [/api/raw-files](https://docs.cloudnet.fmi.fi/api/data-portal.html#get-apiraw-files--upload) endpoint, for example:

https://cloudnet.fmi.fi/api/raw-files?site=cabauw&date=2023-11-26&instrument=parsivel

We have received "20231125_KNMI_Cabauw-CABAUW_PAR002.nc" with checksum "5add012264b6ba69862d1061901494de" but this seems to be an empty netCDF file and it was marked as "invalid", so it's not visible in the API. If you have updated version of the file, please upload it, or try other dates.

**Comment by andrecastro0o** [comment]
@siiptuo, sorry for the late reply :face_with_thermometer: 
And thank you for the clarification on the raw files

I queried the cabauw raw files for disdrometer products, and I only getting files created by other instruments than the disdrometer:

GET: `'/api/raw-files?site=cabauw&date=2023-11-26&product=disdrometer'`), output filtered with `| jq ".[] | {filename,status,instrument}" ` see 
[didrometer_products_cabauw.json](https://github.com/actris-cloudnet/dataportal/files/13545239/didrometer_products_cabauw.json)

And when I query `/api/raw-files?site=cabauw&date=2023-11-26&instrument=parsivel`  or `/api/raw-files?site=cabauw&status=invalid` the response is `[]`

Was the invalid `20231125_KNMI_Cabauw-CABAUW_PAR002.nc` been purged?

**Comment by siiptuo** [comment]
> I queried the cabauw raw files for disdrometer products, and I only getting files created by other instruments than the disdrometer:
> 
> GET: `'/api/raw-files?site=cabauw&date=2023-11-26&product=disdrometer'`), output filtered with `| jq ".[] | {filename,status,instrument}" ` see [didrometer_products_cabauw.json](https://github.com/actris-cloudnet/dataportal/files/13545239/didrometer_products_cabauw.json)

Query parameter `product=disdrometer` only works with `/api/files`. With `/api/raw-files` you need to use `instrument=parsivel` for example. Not really the best validation on our side...

> And when I query `/api/raw-files?site=cabauw&date=2023-11-26&instrument=parsivel` or `/api/raw-files?site=cabauw&status=invalid` the response is `[]`
> 
> Was the invalid `20231125_KNMI_Cabauw-CABAUW_PAR002.nc` been purged?

Yes, but it's possible to send different file for same date if one exists.
