### ISSUE TITLE
quality control error over ACTRIS voc names in InstrumentPID

### ISSUE THREAD

**Issue by andrecastro0o** [actris-cloudnet/dataportal#225]
On https://cloudnet.fmi.fi/file/a65f200e-f33c-4583-aa25-38fc093b59d1/quality  for instrument https://instrumentdb.out.ocp.fmi.fi/instrument/b9ff0d23-9649-49f0-bde2-c1da5adfcab1 (TU Delft RPG-FMCW-94-DP (CLARA-94))

An errors is returned stating that
```
Instrument PID
Test that valid instrument PID exists.
 
 Expected model identifier to be 'https://vocabulary.actris.nilu.no/actris_vocab/RPG-FMCW-94-DP', 'https://vocabulary.actris.nilu.no/actris_vocab/RPG-FMCW-94-DP-S', 'https://vocabulary.actris.nilu.no/actris_vocab/RPG-FMCW-94-SP' or 'https://vocabulary.actris.nilu.no/actris_vocab/RPG-FMCW-94-SP-S' but received 'https://vocabulary.actris.nilu.no/actris_vocab/RPG-FMCW-94S'.
```
Which makes sense, since 
https://vocabulary.actris.nilu.no/actris_vocab/RPG-FMCW-94S is deprecated
                                                                                  
However https://instrumentdb.out.ocp.fmi.fi/instrument/b9ff0d23-9649-49f0-bde2-c1da5adfcab1  is defined with model:
[RPG-FMCW-94-DP-S](https://vocabulary.actris.nilu.no/skosmos/actris_vocab/en/page/RPG-FMCW-94-DP-S)

Hence I am confused why I am seeing  `RPG-FMCW-94S` mentioned in the Quality Control errors

PS: this is not urgent; and I did not make any further investigation, beside what is mentioned in the issue

.

https://vocabulary.actris.nilu.no/actris_vocab/RPG-FMCW-94S
                                                                                 RPG-FMCW-94-DP-S

**Comment by siiptuo** [comment]
Thanks for noticing, this is now fixed! Instrument metadata related to the ePIC PID was outdated, see https://hdl.handle.net/21.12132/3.b9ff0d23964949f0?noredirect
